on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

name: Release policy

jobs:
  test:
    name: run tests and linters
    uses: jvanz/github-actions/.github/workflows/reusable-test-policy-swift.yml@main

  release:
    needs: test
    permissions:
      # Required to create GH releases
      contents: write
      # Required to push to GHCR
      packages: write
      # Required by cosign keyless signing
      id-token: write

    uses: jvanz/github-actions/.github/workflows/reusable-release-policy-swift.yml@main
    with:
      oci-target: ghcr.io/${{ github.repository_owner }}/policies/policy-name # FIXME
