on: [push, pull_request, workflow_dispatch]
name: Continuous integration
jobs:
  test:
    name: run tests and linters
    uses: jvanz/github-actions/.github/workflows/reusable-test-policy-swift.yml@main
